esphome:
  name: radar_sensor_1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Radar Sensor Fallback Hotspot"
    password: !secret fallback_password

logger:

api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80

captive_portal:

binary_sensor:
  - platform: gpio
    name: Radar Motion
    pin: 
      number: GPIO2
      mode: INPUT_PULLDOWN_16
    device_class: motion
    filters:
      delayed_off: 60s